baseURL = 'https://caencamp.github.io/nuit-imagination/'
languageCode = 'fr-fr'
theme = 'soho'
title = "Nuit de l'imaginaire"

enableEmoji = true
summarylength = 10

[params]
author = "CaenCamp"
description = "Le site en 1 heure"

## Set one of:
# gravatar = "soho@example.com"
profilePicture = "images/octocat.png"

copyright = "CaenCamp"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
# themeColor = "#fc2803"

## Set as many as you want.
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "#"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "#"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "#"

[menu]

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/post/"
weight = 100

[[menu.main]]
identifier = "about"
name = "A propos"
url = "/about/"
weight = 300

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[markup]

[markup.highlight]
codeFences = true 
guessSyntax = false 
hl_Lines = "" 
lineNoStart = 1 
lineNos = false 
lineNumbersInTable = true 
noClasses = true # if false, you need to provide you own custom CSS
style = "monokai" 
tabWidth = 4
